import streamlit as st

st.title("我使用的Linux发行版")
st.sidebar.title("我使用的Linux发行版")
st.sidebar.write("1.由课程入门")
st.sidebar.write("2.从主力到弃用")
st.sidebar.write("3.回归双系统")
st.subheader("1.由课程入门", divider=True)
st.write("我入门Linux是因为有课程要用到ROS，ROS虽然有Windows版本但对Windows的支持相对较差，就使用了Ubuntu。Ubuntu使用Gnome桌面，任务栏和软件列表等设计与Windows区别较大，不太习惯。后来课程结束就不再使用Ubuntu了。")
st.write("我使用Ubuntu的体验虽然不太好，但也算是入门了Debian系，了解了apt包管理器、输入法等内容，为后续独立探索其它Linux发行版做了准备。")
st.subheader("2.从主力到弃用", divider=True)
st.write("随着我对开源软件的了解增加，已经在大部分非互联网软件类型中改用开源软件，也希望再次使用开源的Linux系统。")
st.write("查阅资料后，我了解到Linux Mint是易用性较强的Linux发行版，相比大部分发行版外观有一定优势，就安装了Linux Mint22，并成功安装了所有需要使用的软件，部分互联网应用使用星火应用商店安装了wine版本。Linux Mint22使用的是Cinnamon桌面环境，操作上接近Windows系统，使用一些社区主题后总体外观优于当时用的Windows10。当时把Linux Mint22定为主力系统，虽然还有网友反映Windows11稳定性不佳，但考虑到外观优势还是把Windows系统更新到了Windows11。")
st.write("Linux Mint22在使用上也有不少方面体验优于Windows。安装Anaconda后在命令行中可以直接启动Python，而在Windows中需要单独的命令行程序。Linux支持brtfs文件系统，可以实现容量占用较少的快照功能，Linux Mint预装的timeshift能实现按计划创建快照。Cinnamon桌面环境虽然不是轻量化桌面，但流畅度相比Windows系统有优势，窗口可以缩小到较小尺寸并且不会出现还原后尺寸过大的问题。Linux Mint内置应用商店，系统设置中包含换源功能，换源后能快速加载软件详情，我这一时期从软件商店接触到了Xaos、Stellaarium和KDE Marble等优秀的开源软件。在Linux运行Comfyui相比Windows有10%到20%的速度优势，其它软件没有对比。")
st.write("我使用Linux Mint22也遇到了一些问题。Linux Mint内置了smb文件共享功能，但使用其它设备无法连接。Openwebui等在Windows上功能正常的应用也无法在其它设备连接。我用的笔记本电脑的厂商没有适配Linux的风扇转速和键盘灯控制程序，在同类开源软件中也找不到适配的方案。在Windows系统中安装Anaconda后通过conda和pip指令下载都能自动换源，但我在Linux Mint22中只给conda成功换源，pip换源没有效果。Linux上缺少Steam Community302等公开的加速器，在当时对代理服务器了解较少的情况下无法顺利使用GitHub。又因为Windows系统升级到Windows11并使用资源管理器高斯模糊等美化措施后外观有优势，就弃用了Linux。")
st.subheader("3.回归双系统", divider=True)
st.write("后来我了解了代理服务，在完成其它一些项目后有空闲的硬盘，为了进一步探索Linux和在Windows有故障时准备恢复措施，决定安装一个Linux发行版组双系统。")
st.write("开始时为了尝试平铺和浮动兼备的窗口管理，选择了使用测试版Cosmic DE的Pop!_OS。实际使用发现Cosmic DE的窗口管理的确能提高效率，但这一版本的Pop!_OS也存在不少软件无法正常使用，软件安装使用flatpak的空间占用较大，因此决定弃用。")
st.write("个人感觉DDE15桌面的外观比较好，就尝试了GXDE。GXDE是基于Debian12的使用DDE15桌面的Linux发行版，但在GXDE出现无法使用深色模式、系统内置播放器播放HDR视频卡顿的问题。又测试了Debian v23，DDE23桌面的外观不如DDE15，并且使用时遇到了系统内置播放器在界面缩放大于100%时播放视频分辨率下降的问题，也决定弃用了。")
st.write("后面了解到Fedora是偏上游并且易用的系统，使用Budgie桌面的版本操作方式接近Windows并且外观比较好，就安装了Fedora。相比deb系，在软件商店安装软件时不需要输入密码，安装快很多。但使用时遇到一个严重问题：系统自带的硬件解码只支持英特尔处理器，但我的电脑使用的是AMD的处理器，无法使用硬件解码，因此弃用了Fedora。")
st.write("最后还是决定装回Linux Mint，尝试了基于Debian的LMDE6，但出现了安装时没有中文以及部分软件功能不完善的问题（例如Xaos没有提供分形实例），就换成之前用过的Linux Mint22。这一次进一步探索了软件商店中的游戏列表，发现Linux上有比较完善的开源3D游戏，我玩的时间比较长的有Openarena和SuperTuxKart。")